name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  pr:
    strategy:
      matrix:
        step: ['build']
    name: ${{ matrix.step }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'

    - name: Enable Corepack
      run: corepack enable

    - name: Set up correct Yarn version
      run: corepack prepare yarn@4.1.1 --activate

    - name: Install dependencies
      run: yarn install --immutable | grep -v 'YN0013'

    - name: ${{ matrix.step }}
      run: yarn ${{ matrix.step }}
